
audio:
    num_mels: 80
    num_freq: 1025
    sample_rate: 22050
    frame_length_ms: 50
    frame_shift_ms: 12.5
    preemphasis: 0.97
    min_level_db: -100
    ref_level_db: 20
    power: 1.5
    griffin_lim_iters: 60

model:
    optimizer:
        type: "Adam"
        lr: 0.002
        weight_decay: 0.0
        betas: [0.9, 0.999]

    tacotron:
        n_vocab: 250 # Use a larger vocab size is ok.
        embedding_size: 256
        mel_size: 80
        linear_size: 1025
        r: 5

solver:
    # Data config. 
    meta_path: {'train': 'training/meta_train.txt', 'test': 'training/meta_test.txt'}
    data_dir: 'training'
    n_jobs: 4
    # Training config.
    batch_size: 16
    grad_clip: 1.0
    total_steps: 400000
    validation_interval: 2000
    save_checkpoint_interval: 10000
    # log
    log_interval: 10



